unique_ids:
  forms:
    secure.ProductDetailPanel: EEMLQFNQ3ARIELVGMIPXQNOD4IOCKLH4
    secure.ProductShort: GRRPFYPZ4PLHYEXCNMRDOMR3QH6ATORG
    secure.ActiveSubscriptionOptions: YKSFMMLASZQPSBAFRAA5STZ2WIYHDO7A
    secure.SubscriptionList.ItemRowTemplate: 4X72RHVO7YX3NL3LPF7WKG7XDPDS2ZLY
    Login: AQV3FT4ZGKOQFUFRD7RM4SCHDR2SDDDD
    secure.SubscriptionList: PRJGMPJYVNESJRN7HMRUNFIQIU5BPZR5
    secure.HaltedSubscriptionTemplate: NY6QKR5AMYJBGADPJYMNFRXT6GI2BZ2C
    secure.ItemList: OMHCLYTTY6HZKTTJUX4AUZHZGBGZXXFN
    secure.SubscriptionTemplate: 5OSAO4Y7N636AWJCFVYYQ7JFK6757J6F
    secure.ActiveSubscriptionOptions.ActionTemplate: 3BD5LQPMYFINR2HP3LU22AVSG7D4CMLZ
    secure.SubscriptionTemplate.SubPropertyTemplate: 7BP3LJE77TZ6RHFW7IELSA6IDIMWY2FU
    secure.Home: 5GZ7P5A3KVLFD4H3L36HZ3DPVI3FDLWA
    secure.SubscriptionList.SubscriptionRowTemplate: 5ZJX6FULERWNJYNMLW72F7MUX7V5IA2S
    LoginVerify: 7XVM33W7ZX2FVAIUXNSBS6PN4YC7FWOW
    secure.ProductMenuItem: PXF3X7EHOQ2EMOJONHBCKYBVP6OT6FVW
    secure.ProductCard: NE7PKRSSWS35P2RX5BBAFKQKOGF6KKGU
    secure.Status.StatusItemTemplate: 7U6EBJXAFJOZDJ56GIS4JYAZYNU7WNH6
    secure.ActiveSubscriptionOptions.LinkTemplate: DAKMCAFHWHIKX27TXPSIV2275XSMMNWC
    secure.Status: B2MI6KS6R7SFXOLLZRYJNDYLS2YB35LJ
    secure.SubscriptionDetailPanel: WOYR34NOUWR5N5UCKN5GXN2TLVQHEIS6
    secure.ProductList: URR76YKSFZZTHWS34J5CFLX64YKP2TOA
  modules:
    config: B2TWCMQYFD3B4GA5LZVKCZZ23ETQKBCW
    recapcha: 3MVOSTG4K4GJUTCIBXMCAKWPGZOD7YMA
    secure: DGE7YZC2YMFXS2KPBMNZDGLPSNVZLHVV
    secure.services: 3Y3J3XI46VVVOLHSMYRQK4E7FDDXP4G6
    secure.services.auth: ZPX43AMIPCFBMND3DEUTH2ULIYW2RL6C
    secure.services.client: CDAN65VGTIWHYOYXRN7H27XQ6MLAD2UX
    secure.services.utils: JQME3HD6J4RJRDHPBNRPWW2P6LAWHA2C
    secure.services.view: 45QSNTFX7RGQLOL2KL3SE2OTWQEEAVH2
  server_modules:
    services: D2DXBSY4R5S6VWYBP35HOXSEMTFA7H5Q
    services.auth: ZWMLAEJQUERIZDZYCJQR36NZQTJOTN3C
    services.connect: 7HEYEW3WN3UJPSHKA7X3OQ6BITRLCXWK
    services.connect.client: TUAQAO7GBRXXWI7A46G4S7SQ4BX5B22Q
    services.recapcha: 4NXJZWIG5SC6ZSNLDI7TOQ6I6DR5PEVP
    services.secret: SV3AE4XJ3I7S6ERUNAZZZBRQGVPMU64S
    services.subscription: PDPTALOEDMYRHOJMRMCZMRSSG5J64J34
    services.utils: OULNORAWVH4EV7YLYJB2RTE43NSD26Z7
  assets:
    favicon-32x32.ico: TXSK3XE6WP67FUSXQJBFM5MHW4FGEQYW
    standard-page.html: MGPPBS6FSJ6T3JWCVTEJXCJQRJEY55Y5
    theme.css: U4KTZKS34M3XPFMDHQL6LJNWWXAAZFFP
