secret:
  CONNECT_BASE_URL: 'https://portal.cnct.info'
  CONNECT_API_URL: 'https://api.cnct.info/public/v1'
  CONNECT_TOKEN: ''
  AUTH_TOKEN_VALIDITY: '10'
  DEBUG: 'False'
  RECAPTCHA_SECRET: ''
port: '8080'
database: 'jdbc:postgresql://db/customer?user=postgres&password=1q2w3e'
smtp-host: 'smtp.gmail.com'
smtp-port: '465'
smtp-encryption: 'ssl'
smtp-username: '{username}'
smtp-password: '{password}'